class Locators:
    username_input_box = "username"
    password_input_box = "password"
    submit_button = '//*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button'
    variable="//p[@class='oxd-text oxd-text--p oxd-alert-content-text']" 
    pim="//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a"
    deleteemployee="//*[@id='app']/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[9]/div/button[1]/i"
    yesdeleted="//button[@class='oxd-button oxd-button--medium oxd-button--label-danger orangehrm-button-margin']"
    successfullydelete="//*[@id='oxd-toaster_1']/div/div[1]/div[2]/p[2]" 
    editemployeelist="//*[@id='app']/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[9]/div/button[2]/i"
    nickname="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input"
    ssnnumber="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[1]/div/div[2]/input"
    saveemployeelist="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button"
    variable1="//*[@id='oxd-toaster_1']/div/div[1]/div[2]/p[1]"
    addemployee="//button[@class='oxd-button oxd-button--medium oxd-button--secondary']"
    firstname="//input[@class='oxd-input oxd-input--active orangehrm-firstname']"
    lastname="//input[@class='oxd-input oxd-input--active orangehrm-lastname']"
    Checkboxes="//span[@class='oxd-switch-input oxd-switch-input--active --label-right']"
    username="//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[1]/div/div[2]/input"
    password="//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[1]/div/div[2]/input"
    confirmpassword="//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[2]/div/div[2]/input"
    savelist="//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']"
    personalnickname="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input"
    personaldl="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input"
    personalssn="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[1]/div/div[2]/input"
    maleradiobutton="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div/label/span"
    smoker="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div/div[2]/div/div[2]/div/label/span/i"
    savepersonalemployee="//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button"

